### ISSUE TITLE
0.18.0 is not compatible with Ember 1.11

### ISSUE THREAD

**Issue by brendanoh** [ef4/liquid-fire#190] opened 2015-03-02 16:00 UTC
var View = this.container.lookupFactory("view:liquid-if");

Shows error Uncaught TypeError: Cannot read property 'container' of undefined

Not sure what caused this but was hoping someone has experienced similar and can help as it just started happening.

**Comment by conrad-vanl** [comment] 2015-03-03 21:27
This appears to be fixed on latest master. I'm riding on canary ember and noticed the issue as well. 

Related to these two commits:
https://github.com/emberjs/ember.js/commit/5d6353ac51fcdb113eab3e37ee990a4f947d4b74
https://github.com/ef4/liquid-fire/commit/9f6deabb4d7ed0358a328732d99877b30dbfbd73

**Comment by sglanzer** [comment] 2015-03-04 01:55
+1

**Comment by seawatts** [comment] 2015-03-05 23:13
Also getting this with `{{liquid-outlet}}` in application.hbs
ember 1.11.0-beta.4
liquid-fire 0.18.0
`app/transition.js`:
```
export default function() {
  this.transition(
    this.fromRoute('application'),
    this.toRoute('messages'),
    this.use('toLeft')
  );
}
```

**Comment by seawatts** [comment] 2015-03-06 00:18
looks like it's fixed in master

**Comment by ewalti** [comment] 2015-03-10 00:26
I'm getting this with `{{liquid-modal}}` in `application.hbs` with:
ember 1.11.0-beta.5
and liquid-fire 0.18.0

**Comment by sglanzer** [comment] 2015-03-10 03:15
Since this is fixed on master, any chance of a patch release?  I'm firmly committed to using ember 1.11 currently and it would be nice to reference an official release (I can't access github directly from my current environment).

**Comment by ef4** [comment] 2015-03-10 04:23
master has some pretty dramatic changes at the moment, I'm trying to get it 100% feature-complete and documented so I can release.

**Comment by sglanzer** [comment] 2015-03-10 04:25
No problem, I'll wait for the full release then.  Thanks for the great project!

**Comment by e-karma** [comment] 2015-03-18 21:31
Looking forward to this project very much! 
Just did fresh ember-cli app install w/ canary to start learning liquid-fire and i'm getting the same result w/ liquid-outlet.  Would it be wise to wait a week or 2 until changes have settled down?

Thanks @ef4.  Great Ember-conf talk BTW

**Comment by thiagoc7** [comment] 2015-03-20 10:50
I could fix this issue updating `liquid-fire` npm package to github master, with `npm install ef4/liquid-fire `.

**Comment by migace** [comment] 2015-04-02 16:57
Hi thiagoc7! Thank you very much for your work. I can now create a pretty app. So..., good job !

**Comment by brendanoh** [comment] 2015-04-02 19:42
@migace you dont need to point to master now. A normal `npm install liquid-fire` should work. That gets you release 18 which is for 1.11 and above. For 1.10 and below use the 17 branch. 

All the data is here: https://github.com/ef4/liquid-fire#ember-compatibility

Going to close this for now as my original issue is solved.

**Comment by ef4** [comment] 2015-04-02 21:52
Actually I'm not so sure 18 is fully compatible with 1.11. master definitely is, and I am trying to cut a new release as soon as I can.

**Comment by eccegordo** [comment] 2015-04-02 22:00
I can confirm 0.18 does not seem to work with ember 1.11 at least in my specific case. Checking out liquid fire from master did the trick. Look forward to another release.

**Comment by marcemira** [comment] 2015-04-02 23:15
@ef4 Is it possible to release current master as 0.18.1. I'm using it now with stable 1.11.0 and it does work.

**Comment by ef4** [comment] 2015-04-02 23:24
It has a bunch of breaking changes, so it will need to be 0.19.0. 

I need to fix containerless mode, and we need docs updates. Then we can release. If anybody wants to help by updating the docs, the change log mostly points where to go.

**Comment by ef4** [comment] 2015-04-04 09:04
0.19.0 is released.

**Closed by ef4** 2015-04-04 09:04 UTC

**Comment by zjrosen1** [comment] 2015-04-04 09:07
@ef4 You're an animal! Thanks for the release.

**Comment by sglanzer** [comment] 2015-04-04 14:22
@ef4 Thank you so much, I've been looking forward to this release for a
while!  Amazing project!
