### ISSUE TITLE
Modal not working on Ember 1.13.2 and Liquid Fire 0.20.1+

### ISSUE THREAD

**Issue by devlo** [ef4/liquid-fire#323] opened 2015-07-02 10:46 UTC
Modal is working only on Liquid fire 0.20.0 with Ember 1.13.2 
code:
router.js
```
 this.route('test', {path: 'test/:test_id'}, function () {
     this.modal('test-modal', { withParams: 'showTest' });
  });

```

test controller 
```
showTest: false,
actions: {
showTestModal: function () {
        this.set('showTest', true);
      }
}
```

test template
```
<button {{action 'showTestModal'}}>show</button>
```

This works fine in my app in Liquid Fire 0.20.0
Doesn't work on: 0.20.1, 0.20.2, 0.20.3, 0.20.4

It was a problem because on 0.20.0 liquid-spacer doesn't work, i saw commit from #302 fixing liquid-spacer so i've added it to 0.20.0 for now so i could have both working.

**Comment by green-arrow** [comment] 2015-07-07 16:33
Same issue here as well. Except for me, 0.20.0 doesn't fix the modal issue either. When attempting to launch a modal via queryParam, I get:

```
Uncaught TypeError: Cannot read property 'detectNamespace' of undefined - ember.debug.js:50354
```

Attempted to use `master`, but this is still an issue there as well. Using ember 1.13.3.

**Comment by jchn** [comment] 2015-07-13 10:32
Same issue here after updating to ember-cli 1.13.x in liquid-fire 0.20.4

The modals seem to work if I refresh and click the button again, but after navigating a bit, they're not working at other routes, they only seem to work at the route I did the refresh in.

I'm also getting the `detectNamespace` error in 0.20.0

**Comment by ef4** [comment] 2015-07-23 04:44
Yes, I think this is a duplicate of #313. Please reopen if you're still able to reproduce on ember 1.13.5 with liquid-fire 0.21.0 (which I'm about to release).

**Closed by ef4** 2015-07-23 04:44 UTC
