### ISSUE TITLE
liquid-outlet not working in beta?

### ISSUE THREAD

**Issue by ksnyde** [ef4/liquid-fire#216] opened 2015-03-24 08:25 UTC
I have tried to get a very simple configuration working with the latest beta build of Ember but it appears to halt loading templates (aka, the outlet) but without reporting any errors. Is this a know issue? Is there any work-around? 

As for general setup, I'm using:

> ember-cli:  `0.2.1`
> ember: `1.11.0-beta.5.92ef97e6`
> ember-data: `1.0.0-beta.16` (not that this should matter)

WRT to liquid-fire, I started out using `v.0.18.0` but then switched to the latest commits from `@master` as I thought I saw some commits there which I thought might get me over the hump.

**Comment by ksnyde** [comment] 2015-03-24 08:31
Ahh yes and I should add that when I am on `0.18.0` I do get an error:

> Uncaught TypeError: Cannot read property 'container' of undefined

This error goes away when on `@master` but as mentioned above it doesn't load the outlet.

**Comment by ksnyde** [comment] 2015-03-24 08:34
I now remember that it was this thread:

> https://github.com/ef4/liquid-fire/issues/190

which pointed me in the direction of `@master` but unfortunately this was not a magic bullet for me.

**Comment by abarax** [comment] 2015-03-24 17:27
I also have this problem. It has prevented me from upgrading to 1.18.0 and Ember 1.11 beta for now.

**Comment by ef4** [comment] 2015-03-24 17:52
Hmm. I would expect liquid-fire master with ember beta to work. 

 - Does your content render but not animate, or does it not render at all?
 - Is your content in the DOM, but hidden?
 - If you're using master, what sha?

**Comment by ksnyde** [comment] 2015-03-24 20:32
Answer for me are:

- Page renders but {{liquid-outlet}} does not render (on v0.18.0 it didn't load at all)
- As for version, let me get it loaded up again but I'm fairly certain it was on 14752e71d3685c3890a1a9642cbc7c3818567b70 ... give me a sec and should be able to reproduce it on this build (I think)

**Comment by ksnyde** [comment] 2015-03-24 21:00
Confirmed that I'm on 14752e71d3685c3890a1a9642cbc7c3818567b70

**Comment by JFickel** [comment] 2015-03-27 18:22
The liquid-outlet content is in the DOM, but it's hidden.

**Comment by abarax** [comment] 2015-03-30 04:17
Did anyone figure anything out?

**Comment by ksnyde** [comment] 2015-03-30 09:44
@abarax what commit are you on? As mentioned earlier, as of https://github.com/ef4/liquid-fire/commit/14752e71d3685c3890a1a9642cbc7c3818567b70 it was not working for me.

**Comment by ksnyde** [comment] 2015-03-30 10:02
I have upgraded to e8e78a4b2cc83cace039420b48cba20e51e8bcf0 (the latest as of today) and it still doesn't work. :(

**Comment by ef4** [comment] 2015-03-30 14:45
Were you using `containerless=true`? That's changed on master.

Please confirm that your own CSS is not breaking your layout and hiding your content.

**Comment by ksnyde** [comment] 2015-03-30 15:04
Sorry I'm not sure what `containerless=true` is. As for it being my CSS, it seems unlikely considering that as soon as I switch the `{{liquid-outlet}}` back to just a normal `{{outlet}}` everything works fine (albeit without any animation). I have a very similar setup in an older project that's still on the 17.x tag with Ember v8 ... it works fine.

**Comment by ksnyde** [comment] 2015-03-30 15:11
Here's the CSS on the *liquid-container* and *liquid-child* on the 17.x old project that works:

![2015-03-30_16-08-32](https://cloud.githubusercontent.com/assets/980757/6899298/6f803440-d6f7-11e4-9a0f-1f4b3315e282.png)

**Comment by ksnyde** [comment] 2015-03-30 15:16
In comparison, here's a very similarly styled site but using Ember v11 w/ Liquid Fire v18:

![2015-03-30_16-13-57](https://cloud.githubusercontent.com/assets/980757/6899398/13947f46-d6f8-11e4-87a5-54646107b73d.png)

**Comment by ksnyde** [comment] 2015-03-30 15:17
Ok having gone through that it appears to be that the main difference is that the new one has no height component! That *might* be my doing. I'll look at that now but open to any ideas you have too.

> Note: in both cases we have full-screen backgrounds which are being transitioned from page to page.

**Comment by ksnyde** [comment] 2015-03-30 15:24
Well ok, for me my problem is solved. Sorry for pinning the fault on the product. As is often the case the problem was closer to home. :)

In my case I needed the following styling:

	.liquid-container {
		position: absolute;
		top:0;
		left:0;
		width:100%;
		height:100%;
	}
	.liquid-child {
		height: 100%;
	}

**Comment by ef4** [comment] 2015-03-30 15:31
It still sounds like there's a behavior change in liquid fire that exposed this issue. Reopening so we can find and document for other people who may have difficulty upgrading.

**Comment by Samsinite** [comment] 2015-04-01 05:03
I'm getting pretty much the same error(`Uncaught TypeError: Cannot read property 'container' of undefined`), but it instead on the liquid-with [here](https://github.com/ef4/liquid-fire/blob/v0.18.0/app/helpers/liquid-with.js#L7).

**Comment by Samsinite** [comment] 2015-04-01 05:10
I can confirm that master is working fine for me :)

**Comment by al3x-edge** [comment] 2015-04-02 13:53
@ef4, not sure if this is related.  I ran into the same error with ember-intl.  Originally was using `1.1.2` and switched to `1.2.2`. At the location of the error, the container lookup was changed:

 ```js
var intl      = this.container.lookup('intl:main');
``` 
to:

```js
var intl      = view.container.lookup('service:intl');
```

Not sure if the container lookup needs to be done through the view explicitly or not.  Liquid-fire (0.18.0) is using the below while in master it looks like it's completely changed.

```js
var View = this.container.lookupFactory("view:liquid-outlet");
```

Just a stab in the dark and a quick observation I found while upgrading dependencies and node.

**Comment by al3x-edge** [comment] 2015-04-02 14:16
Just as a note, changing `this` to `env.data.view` works although I'm not sure if the view is supposed to be accessed that way or not.  Currently using this in our prototype (manual changes) as moving to master breaks our liquid-if transitions.

**Comment by Kuzirashi** [comment] 2015-04-02 16:36
Ember 1.12-beta.1, `{{liquid-outlet}}` instead of `{{outlet}}` in `application.hbs`:
> Uncaught TypeError: Cannot read property 'container' of undefined

**Comment by ef4** [comment] 2015-04-02 22:16
This is the same issue as https://github.com/ef4/liquid-fire/issues/190, closing in favor of that one.

**Closed by ef4** 2015-04-02 22:16 UTC

**Comment by jondkinney** [comment] 2015-07-13 18:23
@ksnyde thank you very much! I'll prob need to tweak things a bit but your style suggestions got me un-stuck!
